version: '3'

services:
  web:
    build: .
    ports:
      - "8888:3000"

    links:
      - db
    
  db:
    image: mysql
    restart: always
    container_name: godockerDB
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'golangdb'
      # So you don't have to use root, but you can if you like
      #MYSQL_USER: 'root'
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'temp123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'temp123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6666:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: